test_paths:
  - examples/evaluations/evaluate/data_simple.json

auth_config:
  url: https://cpd-cpd-instance-1.apps.mydomain.cp.fyre.ibm.com/orchestrate/cpd-instance-1/instances/yourinstanceid #Your CPD orchestrate instance
  tenant_name: cpd

provider_config:
  provider: "model_proxy"
  model_id: "groq/openai/gpt-oss-120b"

output_dir: "debug-cpd-no-ifm"
wxo_lite_version: 1.12.0
enable_verbose_logging: true